name = "bengilmour-site"
main = "./functions/index.ts"
compatibility_date = "2026-06-13"

[type="javascript"]
  content = "service-worker"

[site]
  bucket = "./public"
  entry-point = "functions"

[assets]
  binding = "PUBLIC_ASSETS"
  directory = "./public"
